logging:
  level:
    org.springframework.cache: INFO
    org.springframework.data.redis.core: INFO

server:
  port: 10002

spring:
  application:
    name: ${rootProject.name}
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 1s
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1124MB
  threads:
    virtual:
      enabled: true
  task:
    execution:
      thread-name-prefix: reco-eng-vt-
    scheduling:
      thread-name-prefix: reco-eng-sched-
  data:
    redis:
      host: transmgmt-prd-cache.aoghs6.ng.0001.apse1.cache.amazonaws.com
      port: 6379
      ssl:
        enabled: true
    mongodb:
      uri: mongodb+srv://username:password@production-titan-cluste.ysuki.mongodb.net/mw-recommendation-engine?authSource=admin&retryWrites=true&w=majority&appName=prod-titan-recommendation-engine
      auto-index-creation: true
  rabbitmq:
    addresses: amqps://b-ec3ceafe-5cf2-4a68-a93a-97cdc4e37a94.mq.ap-southeast-1.on.aws:5671
    username: mwrabbitadmin
    password: MfEFwTTS@so^ry8\$
    virtual-host: inventory
    connection-timeout: 15000
    ssl:
      enabled: true
      verify-hostname: false
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2

management:
  server:
    port: 8200
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${rootProject.name}
      namespace: NA
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - env
          - metrics
          - prometheus
          - threaddump
          - heapdump

aws:
  s3:
    brand:
      endpoint: http://production-s3-endpoint:9000
      access-key: admin
      secret-key: PRODUCTION_SECRET
      region: us-east-1
      bucket-name: brand-logo-bucket
      parent-directory: /production/logos

brand-lib:
  file:
    allowed-extensions: .jpg,.jpeg,.png

# Security / IAM (OAuth2 Resource Server)
mw-recommendation-engine:
  management:
    credentials:
      username: admin
      password: ac412243-acc5-4d05-93df-bf768577e69d
  iam:
    service-url: https://auth-api-prd.movingwalls.com
    product-id: 3078b150-7e3c-4303-bc2c-bbc3df829b2f

# RabbitMQ Configuration
rabbitmq:
  inventory:
    exchange:
      name: inventory-detail.change.event
    queue:
      name: inventory-detail.change.event.recommendation
  audience:
    exchange:
      name: audience.exchange
    queue:
      name: recommendation.engine.audience.queue
  brand:
    exchange:
      name: brand.exchange
    queue:
      name: recommendation.engine.brand.queue
  booking:
    exchange:
      name: booking.exchange
    queue:
      name: recommendation.engine.booking.queue
