sonar.projectKey=mw-planner-frontend
sonar.host.url=https://sq.movingwalls.com
sonar.qualitygate.wait=true

# Coverage report paths
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Coverage exclusions
# sonar.coverage.exclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.js,src/**/*.spec.jsx,src/**/*.spec.ts,src/**/*.spec.tsx,src/test/**,src/**/__tests__/**,src/**/__mocks__/**


sonar.coverage.exclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.js,src/**/*.cjs,src/**/*.ts,src/**/__tests__/**
