global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'mw-planner-scraper'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8100', 'localhost:8100', '47.129.204.148:8100']
