sonar.projectKey=MW-Planner-BackEnd
sonar.projectName=MW-Planner-BackEnd
sonar.host.url=https://sq.movingwalls.com
sonar.qualitygate.wait=true
sonar.java.source=21
sonar.java.binaries=build/classes/java/main
sonar.java.test.binaries=build/classes/java/test,build/classes/java/integrationtest
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=**/config/**,**/constants/**,**/dto/**,**/domain/**,**/enums/**,**/exception/**,**/MwPlannerApplication.java
